In [7]:
import numpy as np 
a = np.array([1 , 2, 3, 4])
z = np.zeros((2 , 3))
o = np.ones(5)
r =np.arange(0,10,2)
l = np.linspace(0,1,5)
rnd = np.random.rand(3,3)
print (a)
print (z)
print (o)
print (r)
print (l)
print (rnd)

[1 2 3 4]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.8738705  0.721038   0.84505765]
 [0.42994596 0.70337369 0.36884255]
 [0.52509775 0.90117135 0.54411533]]


In [13]:
m = np.array([[1,2,3],[4,5,6]])
print (m.shape)
print (m[0,2])
print(m[: ,1])
print(m[1 ,:])

(2, 3)
3
[2 5]
[4 5 6]


In [17]:
a = np.array([1,2,3,4])
print(a*2)
print(a+a)
print(a.mean())
print(a[a>2])

[2 4 6 8]
[2 4 6 8]
2.5
[3 4]


In [18]:
matrix = np.array([[1,2,3],[4,5,6]])
row = np.array([10,20,30])
print(matrix + row)

[[11 22 33]
 [14 25 36]]


In [38]:
# step 1+2+3

matrix = np.array([[5,6,8,1],[10,4,2,11],[12,13,14,15],[4,6,10,8]])
#step1
print(f"shape : ",matrix.shape)
print(f"data type :",matrix.dtype)

#step 2
print(matrix[:,2])
print(matrix[3,:])

#step 3
print (f"matrix mean = ",matrix.mean())
print (matrix[matrix.mean()<matrix])

shape :  (4, 4)
data type : int64
[ 8  2 14 10]
[ 4  6 10  8]
matrix mean =  8.0625
[10 11 12 13 14 15 10]


In [39]:
#step 4
array1 = np.array([[3,4,5,6],[1,10,5,9]])
array2 = np.array([6,8,2,4])
print (array1 + array2)

[[ 9 12  7 10]
 [ 7 18  7 13]]
